### ISSUE TITLE
Update Introduction Text

### ISSUE THREAD

**Issue by alexandra-rhodium** [augusta-company/covid-caribbean#11]
This self-assessment tool will help determine whether you may need further evaluation or testing for COVID-19. You can complete this assessment for yourself, or on behalf of someone else.

START QUIZ

If you have respiratory symptoms and a serious ongoing condition, or are in the third trimester of pregnancy, please follow the advice of your specialist.

Most people do not need to be tested for COVID-19 because it will not change your care.

**People who do not need to be tested for COVID-19 include:**
People without symptoms
People who have mild respiratory symptoms that can be managed at home

Anyone who has symptoms - including a fever, cough, sneezing, or sore throat - should self-isolate and immediately contact the listed hotlines. Continue to complete this assessment to determine if you may need care.

LAST UPDATED:

**Comment by KerronKing** [comment]
Specified change can be found in the commit 221412e07398c4a35df966ebb6cabb15c9b6aeed
