### ISSUE TITLE
Update Text on Questions and Concerns

### ISSUE THREAD

**Issue by alexandra-rhodium** [augusta-company/covid-caribbean#12]
Note: Phone numbers should be hyperlinked to call directly from the form.

OLD TEXT
For questions of concerns, the Trinidad and Tobago Ministry of Health has a COVID-19 Hotline: 877-9355 (877-WELL), and the South-West Regional Health Authority COVID-19 Hotline: 877-9724 (87-SWRHA)

Social Media Available as well: (Facebook, Twitter, Website)

For the most up to date non-medical information, including confirmed cases, travel restrictions, news, and updates you can visit Trinidad and Tobago’s COVID-19 Support and Information.

NEW TEXT
The Trinidad and Tobago Ministry of Health has implemented hotlines for questions and concerns. These hotlines are staffed by a team of medical professionals and are available 24/7.   
COVID-19 National Hotline - 877-9355 (877-WELL)
Southwest Region -  877-9724 (87-SWRHA) 
Tobago - 800-4325( 800-HEAL)

  Social media 
[Facebook](https://www.facebook.com/MinistryofHealthTT/)
[Twitter](https://twitter.com/MOH_TT)
[Website](https://www.health.gov.tt/sitepages/default.aspx?id=292)  

For the most up to date non-medical information, including confirmed cases, travel restrictions, news, and updates you can visit [Trinidad and Tobago’s COVID-19 Support and Information.](http://www.health.gov.tt/sitepages/default.aspx?id=292)

**Comment by KerronKing** [comment]
Updated the text in this section as seen in the following commit: bd95d3464fc5f1965ef71027fdcede5cdd55afa3
