### ISSUE TITLE
Update Questions 1, 2, 3 Text

### ISSUE THREAD

**Issue by alexandra-rhodium** [augusta-company/covid-caribbean#14]
New Text:
**Question One** 
Are you experiencing **fever** and any of the following:
Severe difficulty breathing (e.g. struggling to breathe or speaking in single words)
Severe chest pain
Having a very hard time waking up
Feeling confused
Losing consciousness

**Question Two**
Are you experiencing any of the following:
Mild to moderate shortness of breath
Inability to lie down because of difficulty breathing
Chronic health conditions that you are having difficulty managing because of difficulty breathing

**Question Three**
Are you experiencing any of the following:
Fever
Cough
Sneezing
Sore throat

**Comment by KerronKing** [comment]
See commit b4b75188da5a1eb2cab7d45f453c9166c6443e28 for specified changes.
