### ISSUE TITLE
Update  "Please Stay At Home, Continue Self-Assessment Quiz" Results Text 

### ISSUE THREAD

**Issue by alexandra-rhodium** [augusta-company/covid-caribbean#19]
**New Text**
Please stay at home. As a precaution, the Ministry of Health is asking anyone with mild symptoms (fever, cough, sneezing, or sore throat) to stay home.  
Please contact the hotline below, and a medical professional will advise you regarding isolation and notice to employers. 
  COVID-19 National Hotline - 877-9355 (877-WELL) 
Southwest Region - 877-9724 (87-SWRHA) 
Tobago - 800-4325( 800-HEAL)

**Your self-assessment is not complete. Finish the remaining questions to obtain complete recommendations on what steps you should take**

**OLD TEXT:**
As a precaution, the Ministry of Health is asking anyone with symptoms (fever, cough, sneezing, or sore throat) to stay home for 14 days. If your symptoms worsen, call your family physician. If you are unable to reach your regular health care provider, call877-9355 (WELL) to speak with a health representative.

Your self-assessment is not complete. Finish the remaining questions to obtain complete recommendations on what steps you should take.

**Comment by KerronKing** [comment]
See commit 43d310a0da0552770fc72032a0390a20b7cc77e4 for the relevant change.
