### ISSUE TITLE
Update "Please Stay At Home and Consult Hotline Numbers"  Result  Text

### ISSUE THREAD

**Issue by alexandra-rhodium** [augusta-company/covid-caribbean#20]
*New Text*
Please stay at home,  and please consult one of the below hotlines:   
  COVID-19 National Hotline - 877-9355 (877-WELL) 
Southwest Region - 877-9724 (87-SWRHA) 
Tobago - 800-4325( 800-HEAL)   

If your symptoms worsen, please check back in.
Because you have (or had) symptoms, you should self-isolate.. That means not going to any public places, staying at home, and not having any visitors. Don’t share personal items like dishes, utensils, or towels, and wash your hands often.

Please do not go to an emergency department, family doctor or walk-in clinic unless your symptoms worsen. If you do need to visit an emergency department, family doctor, or walk-in clinic, please call ahead and tell them your symptoms, any international travel within 14 days, and whether you have had close contact with a suspected or confirmed case of COVID-19.

If you need more information go to [TNT COVID-19 Website](http://www.health.gov.tt/sitepages/default.aspx?id=292)

If your symptoms worsen, or if you are concerned, you can return to this self-assessment at any time; 

OLD TEXT:
🙆 Please self-isolate for 14 days. If your symptoms worsen, please check back in.
Because you have (or had) symptoms, you should self-isolate for 10 days. That means not going to any public places, staying at home, and not having any visitors. Don’t share personal items like dishes, utensils, or towels, and wash your hands often.

Please do not go to an emergency department, family doctor or walk-in clinic unless your symptoms worsen. If you do need to visit an emergency department, family doctor, or walk-in clinic, please call ahead and tell them your symptoms, any international travel within 14 days, and whether you have had close contact with a suspected or confirmed case of COVID-19.

If you need more information go to TNT COVID-19 Website.

If your symptoms worsen, or if you are concerned, you can return to this self-assessment at any time; or, call 877 WELL.

For Global News The World Health Organization has created a phone service to provide non-medical information about COVID-19. Information is available via text message or Whatsapp or at +41 79 893 18 92.

**Comment by KerronKing** [comment]
Specified changes can be seen on the following commit: 43d310a0da0552770fc72032a0390a20b7cc77e4
