### ISSUE TITLE
Update "Please Stay At Home - No Testing Required" Text

### ISSUE THREAD

**Issue by alexandra-rhodium** [augusta-company/covid-caribbean#21]
**New Text**

Please stay at home . You do not need testing for COVID-19.
Since you don't have symptoms, you do not need testing for COVID-19 at this time. However, there’s a chance you could get sick since your exposure. You should self-monitor for any symptoms (fever, cough, sneezing, sore throat, or difficulty breathing). If you begin to develop these, you should take this self-assessment again.
If you are a health care worker, follow the advice of your employer.
If you need more information, go to [TNT COVID-19 Website](http://www.health.gov.tt/sitepages/default.aspx?id=292)

**OLD TEXT**

🙆 Please self-isolate for 14 days. You do not need testing for COVID-19.
Since you don't have symptoms, you do not need testing for COVID-19 at this time. However, there’s a chance you could get sick since it’s less than 14 days since your exposure. You should self-monitor for any symptoms (fever, cough, sneezing, sore throat, or difficulty breathing). If you begin to develop these, you should take this self-assessment again.

If you are a health care worker, follow the advice of your employer.

If you need more information go to TNT COVID-19 Website.

If you are experiencing symptoms other than COVID-19, contact your family physician. If you are unable to reach your regular health care provider, call 877-9355 (WELL) to speak with a health representative.

For Global News The World Health Organization has created a phone service to provide non-medical information about COVID-19. Information is available via text message or Whatsapp or at +41 79 893 18 92.

**Comment by yonis9** [comment]
Hi, where is the older text that you want to update?

**Comment by turbosnail9** [comment]
Hi Yoni! It's the the very last question. See the image below:

![](https://i.imgur.com/KOIKItZ.png)

**Comment by yonis9** [comment]
OK I'm working on it
