### ISSUE TITLE
Improve spacing in header and footer

### ISSUE THREAD

**Issue by turbosnail9** [augusta-company/covid-caribbean#6]

**Comment by yonis9** [comment]
Hi, can I take it?

**Comment by turbosnail9** [comment]
Hi Yoni!

Yes of course. We’d love your help. Please work on your own branch and then issue a pull request when you’re ready to merge.

Cheers,
Ari

*Ari Ramdial*
Heretic

C: 514-817-9099

( http://maps.google.com/maps?q=&hl=en )
